title: Blog Bibliotheks- und Archivinformatik
author: Stephanie
email: stephanie.riebe@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2021

# social links
github_username: StRiebe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
